version: '3.8'

services:
  php-apache:
    build:
      context: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: multivendor_ecommerce
      DB_USERNAME: root
      DB_PASSWORD: 1212  
      DB_ROOT_PASSWORD: 1212


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: multivendor_ecommerce
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_PASSWORD: 1212
    volumes:
      - db_data:/var/lib/mysql
    

volumes:
  db_data:




