version: '3.8'

services:
  php-apache:
    build:
      context: .
    container_name: php-apache
    ports:
      - "8080:80"  # Keep this for internal communication
    volumes:
      - ./apache-config/ports.conf:/etc/apache2/ports.conf
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: multivendor_ecommerce
      DB_USERNAME: root
      DB_PASSWORD: 1212  
      DB_ROOT_PASSWORD: 1212
    deploy:
      resources:
        limits:
          cpus: '0.5'  
          memory: 512M  
        reservations:
          cpus: '0.25'
          memory: 256M

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: multivendor_ecommerce
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_PASSWORD: 1212
    volumes:
      - db_data:/var/lib/mysql
    
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Route HTTP traffic to Nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  # Enable Nginx to read Docker events
    depends_on:
      - php-apache

volumes:
  db_data:
